---
# file: roles/postgres/tasks/main.yml



- name: ensure common packages are present
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - python-psycopg2

- name: ensure the client authentication configuration file is present
  template: src=etc/postgresql/9.3/main/pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify: restart postgresql

- meta: flush_handlers
